### ISSUE TITLE
Add comments to your blog via "Utterances" so I can reply to your request for comments

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [nelhage/blog.nelhage.com#3]
Great article: https://blog.nelhage.com/2010/06/i-hate-code-review/

You said: 

> I'd like to hear your thoughts: Does code review work for you?

I feel the same way. I'd like to tell you that by leaving a comment, but I can't. Please add the "Utterances" Issue-based commenting system to your blog so I can. 

Here is how: my answer on [How to add comments in blog posts on Github-pages websites](https://webapps.stackexchange.com/q/165528/126659)

**Comment by nelhage** [comment]
I'm not going to host a comments section on my blog. You're welcome to make your own post in response, though!

**Comment by ElectricRCAircraftGuy** [comment]
If I may ask: why don't you want a comments section on your blog? 

I see a lot of benefits to one.
